listener 1883 127.0.0.1

listener 8883
certfile /mosquitto/certs/server.crt
keyfile /mosquitto/certs/server.key
require_certificate false

plugin /usr/lib/mosquitto_dynamic_security.so
plugin_opt_config_file /mosquitto/dynsec/dynamic-security.json

persistence true
persistence_location /mosquitto/data/

log_dest stdout
log_type error warning notice information