spring:
  main:
    web-application-type: none
  flyway:
    enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  task:
    scheduling:
      pool:
        size: 1

springdoc:
  api-docs:
    enabled: false
