package com.dompetgaruda.api.qrpayment;

import com.dompetgaruda.api.common.entity.Device;
import com.dompetgaruda.api.common.repository.DeviceRepository;
import com.dompetgaruda.api.mqtt.MqttPublisherService;
import com.dompetgaruda.api.qrpayment.dto.CreatePaymentRequestRequest;
import com.dompetgaruda.api.qrpayment.dto.CreatePaymentRequestResponse;
import com.dompetgaruda.api.qrpayment.dto.PayPaymentRequestResponse;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Profile;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;

import java.util.UUID;

/**
 * FR20/FR21 — Bayar QR Online. Create identifies the receiver via a {@code Receiver-Device-Id}
 * header; pay identifies the payer via a {@code Payer-Device-Id} header. Neither endpoint uses
 * a device Bearer token (CLAUDE.md §1a — bare device-id lookup, same pattern as TransferController).
 *
 * <p>Not the national QRIS standard — settles entirely inside this system's own ledger
 * (CLAUDE.md §1). Swagger tag is deliberately "Bayar QR", never "QRIS".
 */
@RestController
@RequestMapping("/device/payment-request")
@Profile("api")
@Tag(name = "Bayar QR", description = "Device-facing Bayar QR Online endpoints.")
public class PaymentRequestController {

    private final DeviceRepository deviceRepository;
    private final PaymentRequestService service;
    // Null in the api profile today — same documented limitation as TransferController.
    @Autowired(required = false)
    private MqttPublisherService mqttPublisher;

    public PaymentRequestController(DeviceRepository deviceRepository, PaymentRequestService service) {
        this.deviceRepository = deviceRepository;
        this.service = service;
    }

    @PostMapping
    @ResponseStatus(HttpStatus.CREATED)
    @Operation(
            summary = "Create a Bayar QR Online payment request (FR20)",
            description = "The named receiver device's owning user becomes the receiver. Returns a QR-encodable payload the payer scans.")
    @ApiResponses({
            @ApiResponse(responseCode = "201", description = "Payment request created."),
            @ApiResponse(responseCode = "400", description = "amount <= 0."),
            @ApiResponse(responseCode = "401", description = "Missing Receiver-Device-Id header, or device not registered/not ACTIVE.")
    })
    public CreatePaymentRequestResponse create(
            @Parameter(description = "Receiving device's id (CLAUDE.md §1a). Required — identifies the receiving device and its owning user.", required = true)
            @RequestHeader(name = "Receiver-Device-Id", required = false) String receiverDeviceId,
            @RequestBody CreatePaymentRequestRequest request) {
        Device device = resolveDeviceById(receiverDeviceId);
        return service.create(device, request);
    }

    @PostMapping("/{requestId}/pay")
    @Operation(
            summary = "Pay a Bayar QR Online payment request (FR21)",
            description = "Synchronous, server-mediated settlement. Debits the payer's ONLINE ledger account and " +
                          "credits the receiver's in one DB transaction. A repeated Idempotency-Key for the same " +
                          "device returns the original response without creating a second posting.")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Payment posted (or replayed from a prior identical Idempotency-Key)."),
            @ApiResponse(responseCode = "400", description = "Missing/invalid Idempotency-Key, or self-payment."),
            @ApiResponse(responseCode = "401", description = "Missing Payer-Device-Id header, or device not registered/not ACTIVE."),
            @ApiResponse(responseCode = "404", description = "requestId does not exist."),
            @ApiResponse(responseCode = "409", description = "Request is already PAID or already EXPIRED."),
            @ApiResponse(responseCode = "410", description = "Request just expired (detected at pay time); now marked EXPIRED."),
            @ApiResponse(responseCode = "422", description = "Insufficient payer online balance.")
    })
    public ResponseEntity<PayPaymentRequestResponse> pay(
            @Parameter(description = "Paying device's id (CLAUDE.md §1a). Required — identifies the paying device and its owning user.", required = true)
            @RequestHeader(name = "Payer-Device-Id", required = false) String payerDeviceId,
            @Parameter(description = "UUID v4 generated by the device. Required — a missing header is a 400.", required = true)
            @RequestHeader(name = "Idempotency-Key", required = false) String idempotencyKeyHeader,
            @PathVariable UUID requestId) {

        Device device = resolveDeviceById(payerDeviceId);
        UUID idempotencyKey = parseIdempotencyKey(idempotencyKeyHeader);

        PayOutcome outcome = service.pay(device, requestId, idempotencyKey);

        if (outcome.newlyProcessed() && outcome.receiverDeviceId() != null && mqttPublisher != null) {
            mqttPublisher.publishPaymentReceived(
                    outcome.receiverDeviceId(), outcome.body().transactionId());
        }

        return ResponseEntity.status(outcome.status()).body(outcome.body());
    }

    private UUID parseIdempotencyKey(String header) {
        if (header == null || header.isBlank()) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Idempotency-Key header is required");
        }
        try {
            return UUID.fromString(header.strip());
        } catch (IllegalArgumentException e) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Idempotency-Key must be a valid UUID");
        }
    }

    private Device resolveDeviceById(String deviceId) {
        if (deviceId == null || deviceId.isBlank()) {
            throw new ResponseStatusException(HttpStatus.UNAUTHORIZED, "Missing device id header");
        }
        return deviceRepository.findById(deviceId)
                .filter(d -> "ACTIVE".equals(d.getStatus()))
                .orElseThrow(() -> new ResponseStatusException(
                        HttpStatus.UNAUTHORIZED, "Invalid device id"));
    }
}
