package com.dompetgaruda.api.qrpayment;

import com.dompetgaruda.api.auth.DeviceTokenVerifier;
import com.dompetgaruda.api.common.entity.Device;
import com.dompetgaruda.api.mqtt.MqttPublisherService;
import com.dompetgaruda.api.qrpayment.dto.CreatePaymentRequestRequest;
import com.dompetgaruda.api.qrpayment.dto.CreatePaymentRequestResponse;
import com.dompetgaruda.api.qrpayment.dto.PayPaymentRequestResponse;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Profile;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;

import java.util.UUID;

/**
 * FR20/FR21 — Bayar QR Online. Requires a device Bearer token.
 *
 * <p>Not the national QRIS standard — settles entirely inside this system's own ledger
 * (CLAUDE.md §1). Swagger tag is deliberately "Bayar QR", never "QRIS".
 */
@RestController
@RequestMapping("/device/payment-request")
@Profile("api")
@Tag(name = "Bayar QR", description = "Device-facing Bayar QR Online endpoints — authenticate with a device Bearer token.")
public class PaymentRequestController {

    private final DeviceTokenVerifier verifier;
    private final PaymentRequestService service;
    // Null in the api profile today — same documented limitation as TransferController.
    @Autowired(required = false)
    private MqttPublisherService mqttPublisher;

    public PaymentRequestController(DeviceTokenVerifier verifier, PaymentRequestService service) {
        this.verifier = verifier;
        this.service = service;
    }

    @PostMapping
    @ResponseStatus(HttpStatus.CREATED)
    @Operation(
            summary = "Create a Bayar QR Online payment request (FR20)",
            description = "The authenticated device's owning user becomes the receiver. Returns a QR-encodable payload the payer scans.")
    @ApiResponses({
            @ApiResponse(responseCode = "201", description = "Payment request created."),
            @ApiResponse(responseCode = "400", description = "amount <= 0."),
            @ApiResponse(responseCode = "401", description = "Missing or invalid device Bearer token.")
    })
    public CreatePaymentRequestResponse create(
            @RequestHeader(name = HttpHeaders.AUTHORIZATION, required = false) String authHeader,
            @RequestBody CreatePaymentRequestRequest request) {
        Device device = resolveDevice(authHeader);
        return service.create(device, request);
    }

    @PostMapping("/{requestId}/pay")
    @Operation(
            summary = "Pay a Bayar QR Online payment request (FR21)",
            description = "Synchronous, server-mediated settlement. Debits the payer's ONLINE ledger account and " +
                          "credits the receiver's in one DB transaction. A repeated Idempotency-Key for the same " +
                          "device returns the original response without creating a second posting.")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Payment posted (or replayed from a prior identical Idempotency-Key)."),
            @ApiResponse(responseCode = "400", description = "Missing/invalid Idempotency-Key, or self-payment."),
            @ApiResponse(responseCode = "401", description = "Missing or invalid device Bearer token."),
            @ApiResponse(responseCode = "404", description = "requestId does not exist."),
            @ApiResponse(responseCode = "409", description = "Request is already PAID or already EXPIRED."),
            @ApiResponse(responseCode = "410", description = "Request just expired (detected at pay time); now marked EXPIRED."),
            @ApiResponse(responseCode = "422", description = "Insufficient payer online balance.")
    })
    public ResponseEntity<PayPaymentRequestResponse> pay(
            @RequestHeader(name = HttpHeaders.AUTHORIZATION, required = false) String authHeader,
            @Parameter(description = "UUID v4 generated by the device. Required — a missing header is a 400.", required = true)
            @RequestHeader(name = "Idempotency-Key", required = false) String idempotencyKeyHeader,
            @PathVariable UUID requestId) {

        Device device = resolveDevice(authHeader);
        UUID idempotencyKey = parseIdempotencyKey(idempotencyKeyHeader);

        PayOutcome outcome = service.pay(device, requestId, idempotencyKey);

        if (outcome.newlyProcessed() && outcome.receiverDeviceId() != null && mqttPublisher != null) {
            mqttPublisher.publishPaymentReceived(
                    outcome.receiverDeviceId(), outcome.body().transactionId());
        }

        return ResponseEntity.status(outcome.status()).body(outcome.body());
    }

    private UUID parseIdempotencyKey(String header) {
        if (header == null || header.isBlank()) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Idempotency-Key header is required");
        }
        try {
            return UUID.fromString(header.strip());
        } catch (IllegalArgumentException e) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Idempotency-Key must be a valid UUID");
        }
    }

    private Device resolveDevice(String authHeader) {
        String rawToken = null;
        if (authHeader != null && authHeader.startsWith("Bearer ")) {
            rawToken = authHeader.substring(7).strip();
        }
        return verifier.verify(rawToken)
                .orElseThrow(() -> new ResponseStatusException(
                        HttpStatus.UNAUTHORIZED, "Invalid device token"));
    }
}
