package com.dompetgaruda.api.transfer;

import com.dompetgaruda.api.auth.DeviceTokenVerifier;
import com.dompetgaruda.api.common.entity.Device;
import com.dompetgaruda.api.mqtt.MqttPublisherService;
import com.dompetgaruda.api.transfer.dto.TransferRequest;
import com.dompetgaruda.api.transfer.dto.TransferResponse;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Profile;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;

import java.util.UUID;

/**
 * FR18/FR19 — {@code POST /device/transfer}. Requires a device Bearer token.
 *
 * <p>{@code @Profile("api")}: online transfers post to the ledger synchronously in the
 * request (CLAUDE.md §3 "Online flows"), unlike the offline sync_inbox pattern.
 */
@RestController
@RequestMapping("/device/transfer")
@Profile("api")
@Tag(name = "Transfer", description = "Device-facing online transfer endpoint — authenticate with a device Bearer token.")
public class TransferController {

    private final DeviceTokenVerifier verifier;
    private final TransferService transferService;
    // Null in the api profile today (MqttPublisherService is @Profile("worker")); best-effort
    // hint only, same limitation as PouchController's cert-refresh publish (CLAUDE.md §8).
    @Autowired(required = false)
    private MqttPublisherService mqttPublisher;

    public TransferController(DeviceTokenVerifier verifier, TransferService transferService) {
        this.verifier = verifier;
        this.transferService = transferService;
    }

    @PostMapping
    @Operation(
            summary = "Transfer funds to another user's online balance (FR18/FR19)",
            description = "Synchronous, server-mediated online transfer. Debits the sender's ONLINE " +
                          "ledger account and credits the receiver's in one DB transaction. A repeated " +
                          "Idempotency-Key for the same device returns the original response without " +
                          "creating a second posting.")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Transfer posted (or replayed from a prior identical Idempotency-Key)."),
            @ApiResponse(responseCode = "400", description = "Missing/invalid Idempotency-Key, self-transfer, or amount out of bounds."),
            @ApiResponse(responseCode = "401", description = "Missing or invalid device Bearer token."),
            @ApiResponse(responseCode = "404", description = "receiverUserId does not exist."),
            @ApiResponse(responseCode = "422", description = "Insufficient sender online balance.")
    })
    public ResponseEntity<TransferResponse> transfer(
            @RequestHeader(name = HttpHeaders.AUTHORIZATION, required = false) String authHeader,
            @Parameter(description = "UUID v4 generated by the device. Required — a missing header is a 400, never a silent default.", required = true)
            @RequestHeader(name = "Idempotency-Key", required = false) String idempotencyKeyHeader,
            @RequestBody TransferRequest request) {

        Device device = resolveDevice(authHeader);
        UUID idempotencyKey = parseIdempotencyKey(idempotencyKeyHeader);

        TransferOutcome outcome = transferService.transfer(device, idempotencyKey, request);

        if (outcome.newlyProcessed() && outcome.receiverDeviceId() != null && mqttPublisher != null) {
            mqttPublisher.publishPaymentReceived(
                    outcome.receiverDeviceId().toString(), outcome.body().transactionId());
        }

        return ResponseEntity.status(outcome.status()).body(outcome.body());
    }

    private UUID parseIdempotencyKey(String header) {
        if (header == null || header.isBlank()) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Idempotency-Key header is required");
        }
        try {
            return UUID.fromString(header.strip());
        } catch (IllegalArgumentException e) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Idempotency-Key must be a valid UUID");
        }
    }

    private Device resolveDevice(String authHeader) {
        String rawToken = null;
        if (authHeader != null && authHeader.startsWith("Bearer ")) {
            rawToken = authHeader.substring(7).strip();
        }
        return verifier.verify(rawToken)
                .orElseThrow(() -> new ResponseStatusException(
                        HttpStatus.UNAUTHORIZED, "Invalid device token"));
    }
}
